In [ ]:
import pandas as pd

data1 = pd.read_feather('/content/drive/MyDrive/기업연계 프로젝트/lending_club_clean_v3_1_N.feather')
data2 = pd.read_feather('/content/drive/MyDrive/기업연계 프로젝트/lending_club_clean_v3_2_N.feather')

In [ ]:
pd.set_option('display.max_columns', None)

In [ ]:
data1.head()

,id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,fico_range_low,fico_range_high,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,last_fico_range_high,last_fico_range_low,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_fico_range_low,sec_app_fico_range_high,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,loan_status_N,state,new_total_rev_hi_lim,new_revol_bal,new_revol_util,new_bc_open_to_buy,new_total_bc_limit,new_bc_util,new_all_util,new_state,new_purpose,new_emp_length,new_home_ownership,new_verification_status
0,1077501,5000,5000,4975.0,36,0.1065,162.869995,B,B2,NaN,10+ years,RENT,24000.0,Verified,2011-12-01,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,credit_card,Computer,860,AZ,27.650000,0,1985-01-01,735,739,1,-1,-1,3,0,13648,0.837,9,f,0.0,0.0,5863.155273,5833.839844,5000.000000,863.159973,0.000000,0.000000,0.00,2015-01-01,171.619995,NaT,2020-05-01,704,700,0,-1,1,Individual,5692.509766,-1.0,NaN,0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1.0,0,0,-1,0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1.0,-1.0,0,0,-1,-1,-1,-1,-1,539,543,NaT,-1,-1,-1,-1.0,-1,-1,-1,-1,N,NaN,NaN,NaN,-1,-1.0,NaT,NaT,NaT,-1,-1,NaN,-1.0,-1.0,-1.0,N,1,AZ,16305.855161,13648.0,0.837,-1.01,-0.99,-1.0,83.698996,2,1,12,1,1
1,1077430,2500,2500,2500.0,60,0.1527,59.830002,C,C4,Ryder,< 1 year,RENT,30000.0,Source Verified,2011-12-01,Charged Off,n,https://lendingclub.com/browse/loanDetail.acti...,car,bike,309,GA,1.000000,0,1999-04-01,740,744,5,-1,-1,3,0,1687,0.094,4,f,0.0,0.0,1014.530029,1014.530029,456.459991,435.170013,0.000000,122.900002,1.11,2013-04-01,119.660004,NaT,2016-10-01,499,0,0,-1,1,Individual,5692.509766,-1.0,NaN,0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1.0,0,0,-1,0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1.0,-1.0,0,0,-1,-1,-1,-1,-1,539,543,NaT,-1,-1,-1,-1.0,-1,-1,-1,-1,N,NaN,NaN,NaN,-1,-1.0,NaT,NaT,NaT,-1,-1,NaN,-1.0,-1.0,-1.0,N,0,GA,17946.809125,1687.0,0.094,-1.01,-0.99,-1.0,9.394951,2,2,2,1,2
2,1077175,2400,2400,2400.0,36,0.1596,84.330002,C,C5,NaN,10+ years,RENT,12252.0,Not Verified,2011-12-01,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,small_business,real estate business,606,IL,8.720000,0,2001-11-01,735,739,2,-1,-1,2,0,2956,0.985,10,f,0.0,0.0,3005.666748,3005.669922,2400.000000,605.669983,0.000000,0.000000,0.00,2014-06-01,649.909973,NaT,2017-06-01,739,735,0,-1,1,Individual,5692.509766,-1.0,NaN,0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1.0,0,0,-1,0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1.0,-1.0,0,0,-1,-1,-1,-1,-1,539,543,NaT,-1,-1,-1,-1.0,-1,-1,-1,-1,N,NaN,NaN,NaN,-1,-1.0,NaT,NaT,NaT,-1,-1,NaN,-1.0,-1.0,-1.0,N,1,IL,3001.015185,2956.0,0.985,-1.01,-0.99,-1.0,98.499501,2,3,12,1,3
3,1076863,10000,10000,10000.0,36,0.1349,339.309998,C,C1,AIR RESOURCES BOARD,10+ years,RENT,49200.0,Source Verified,2011-12-01,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,other,personel,917,CA,20.000000,0,1996-02-01,690,694,1,35,-1,10,0,5598,0.210,37,f,0.0,0.0,12231.889648,12231.889648,10000.000000,2214.919922,16.969999,0.000000,0.00,2015-01-01,357.480011,NaT,2016-04-01,604,600,0,-1,1,Individual,5692.509766,-1.0,NaN,0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1.0,0,0,-1,0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1.0,-1.0,0,0,-1,-1,-1,-1,-1,539,543,NaT,-1,-1,-1,-1.0,-1,-1,-1,-1,N,NaN,NaN,NaN,-1,-1.0,NaT,NaT,NaT,-1,-1,NaN,-1.0,-1.0,-1.0,N,1,CA,26657.143689,5598.0,0.210,-1.01,-0.99,-1.0,20.997036,2,4,12,1,2
4,1075358,3000,3000,3000.0,60,0.1269,67.790001,B,B5,University Medical Group,1 year,RENT,80000.0,Source Verified,2011-12-01,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,other,Personal,972,OR,17.940001,0,1996-01-01,695,699,0,38,-1,15,0,27783,0.539,38,f,0.0,0.0,4066.908203,4066.909912,3000.000000,1066.910034,0.000000,0.000000,0.00,2017-01-01,67.300003,NaT,2018-04-01,684,680,0,-1,1,Individual,5692.509766,-1.0,NaN,0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1.0,0,0,-1,0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1.0,-1.0,0,0,-1,-1,-1,-1,-1,539,543,NaT,-1,-1,-1,-1.0,-1,-1,-1,-1,N,NaN,NaN,NaN,-1,-1.0,NaT,NaT,NaT,-1,-1,NaN,-1.0,-1.0,-1.0,N,1,OR,51545.451262,27783.0,0.539,-1.01,-0.99,-1.0,53.899109,0,4,3,1,2

In [ ]:
# Int/Float형
nan_in_columns = data1.isna().any()

# 결측값이 있는 열만 선택
nan_in_columns.sum()

15

In [ ]:
# Int/Float형 -> int/float형으로 변환
for column in data1.select_dtypes(include=['Float64', 'float32']).columns:
    data1[column] = data1[column].astype('float64')

for column in data1.select_dtypes(include=['Int16', 'Int32', 'Int64']).columns:
    data1[column] = data1[column].astype('int64')


# → int, float(파이썬 내장 데이터 타입으로 null지원 안함)/Int, Float(판다스 데이터 타입으로 null 지원함)

In [ ]:
# int/float형
nan_in_columns_2 = data1.isna().any()

# 결측값이 있는 열만 선택
nan_in_columns_2.sum()

17

In [ ]:
nan_in_columns[nan_in_columns != nan_in_columns_2]

new_total_rev_hi_lim    False
new_total_bc_limit      False
dtype: bool

In [ ]:
# new_total_bc_limit, new_total_rev_hi_lim

In [ ]:
data2.head()

,id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,fico_range_low,fico_range_high,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,last_fico_range_high,last_fico_range_low,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_fico_range_low,sec_app_fico_range_high,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,loan_status_N,state,new_total_rev_hi_lim,new_revol_bal,new_revol_util,new_bc_open_to_buy,new_total_bc_limit,new_bc_util,new_all_util,new_state,new_purpose,new_emp_length,new_home_ownership,new_verification_status
0,1077501,5000,5000,4975.0,36,0.1065,162.869995,B,B2,NaN,10+ years,RENT,24000.0,Verified,2011-12-01,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,credit_card,Computer,860,AZ,27.650000,0,1985-01-01,735,739,1,-1,-1,3,0,13648,0.837,9,f,0.0,0.0,5863.155273,5833.839844,5000.000000,863.159973,0.000000,0.000000,0.00,2015-01-01,171.619995,NaT,2020-05-01,704,700,0,-1,1,Individual,5692.509766,-1.0,NaN,0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1.0,0,0,-1,0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1.0,-1.0,0,0,-1,-1,-1,-1,-1,539,543,NaT,-1,-1,-1,-1.0,-1,-1,-1,-1,N,NaN,NaN,NaN,-1,-1.0,NaT,NaT,NaT,-1,-1,NaN,-1.0,-1.0,-1.0,N,1,AZ,16305.855161,13648.0,0.837,-1.01,-0.99,-1.0,83.698996,1,1,12,1,1
1,1077430,2500,2500,2500.0,60,0.1527,59.830002,C,C4,Ryder,< 1 year,RENT,30000.0,Source Verified,2011-12-01,Charged Off,n,https://lendingclub.com/browse/loanDetail.acti...,car,bike,309,GA,1.000000,0,1999-04-01,740,744,5,-1,-1,3,0,1687,0.094,4,f,0.0,0.0,1014.530029,1014.530029,456.459991,435.170013,0.000000,122.900002,1.11,2013-04-01,119.660004,NaT,2016-10-01,499,0,0,-1,1,Individual,5692.509766,-1.0,NaN,0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1.0,0,0,-1,0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1.0,-1.0,0,0,-1,-1,-1,-1,-1,539,543,NaT,-1,-1,-1,-1.0,-1,-1,-1,-1,N,NaN,NaN,NaN,-1,-1.0,NaT,NaT,NaT,-1,-1,NaN,-1.0,-1.0,-1.0,N,0,GA,17946.809125,1687.0,0.094,-1.01,-0.99,-1.0,9.394951,1,2,2,1,2
2,1077175,2400,2400,2400.0,36,0.1596,84.330002,C,C5,NaN,10+ years,RENT,12252.0,Not Verified,2011-12-01,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,small_business,real estate business,606,IL,8.720000,0,2001-11-01,735,739,2,-1,-1,2,0,2956,0.985,10,f,0.0,0.0,3005.666748,3005.669922,2400.000000,605.669983,0.000000,0.000000,0.00,2014-06-01,649.909973,NaT,2017-06-01,739,735,0,-1,1,Individual,5692.509766,-1.0,NaN,0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1.0,0,0,-1,0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1.0,-1.0,0,0,-1,-1,-1,-1,-1,539,543,NaT,-1,-1,-1,-1.0,-1,-1,-1,-1,N,NaN,NaN,NaN,-1,-1.0,NaT,NaT,NaT,-1,-1,NaN,-1.0,-1.0,-1.0,N,1,IL,3001.015185,2956.0,0.985,-1.01,-0.99,-1.0,98.499501,1,3,12,1,3
3,1076863,10000,10000,10000.0,36,0.1349,339.309998,C,C1,AIR RESOURCES BOARD,10+ years,RENT,49200.0,Source Verified,2011-12-01,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,other,personel,917,CA,20.000000,0,1996-02-01,690,694,1,35,-1,10,0,5598,0.210,37,f,0.0,0.0,12231.889648,12231.889648,10000.000000,2214.919922,16.969999,0.000000,0.00,2015-01-01,357.480011,NaT,2016-04-01,604,600,0,-1,1,Individual,5692.509766,-1.0,NaN,0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1.0,0,0,-1,0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1.0,-1.0,0,0,-1,-1,-1,-1,-1,539,543,NaT,-1,-1,-1,-1.0,-1,-1,-1,-1,N,NaN,NaN,NaN,-1,-1.0,NaT,NaT,NaT,-1,-1,NaN,-1.0,-1.0,-1.0,N,1,CA,26657.143689,5598.0,0.210,-1.01,-0.99,-1.0,20.997036,1,4,12,1,2
4,1075358,3000,3000,3000.0,60,0.1269,67.790001,B,B5,University Medical Group,1 year,RENT,80000.0,Source Verified,2011-12-01,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,other,Personal,972,OR,17.940001,0,1996-01-01,695,699,0,38,-1,15,0,27783,0.539,38,f,0.0,0.0,4066.908203,4066.909912,3000.000000,1066.910034,0.000000,0.000000,0.00,2017-01-01,67.300003,NaT,2018-04-01,684,680,0,-1,1,Individual,5692.509766,-1.0,NaN,0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1.0,0,0,-1,0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1.0,-1.0,0,0,-1,-1,-1,-1,-1,539,543,NaT,-1,-1,-1,-1.0,-1,-1,-1,-1,N,NaN,NaN,NaN,-1,-1.0,NaT,NaT,NaT,-1,-1,NaN,-1.0,-1.0,-1.0,N,1,OR,51545.451262,27783.0,0.539,-1.01,-0.99,-1.0,53.899109,0,4,3,1,2

In [ ]:
# new가 붙은 변수 찾기
data1.filter(like='new_').columns

Index(['new_total_rev_hi_lim', 'new_revol_bal', 'new_revol_util',
       'new_bc_open_to_buy', 'new_total_bc_limit', 'new_bc_util',
       'new_all_util', 'new_state', 'new_purpose', 'new_emp_length',
       'new_home_ownership', 'new_verification_status'],
      dtype='object')

In [ ]:
cols = [
    'loan_amnt', 'funded_amnt', 'term', 'int_rate', 'installment', 'annual_inc',
    'dti', 'delinq_2yrs', 'earliest_cr_line', 'fico_range_high', 'open_acc', 'pub_rec',
    'total_acc', 'inq_fi',
    'total_cu_tl', 'mo_sin_old_il_acct',
    'mo_sin_old_rev_tl_op', 'mort_acc', 'num_accts_ever_120_pd', 'num_bc_sats',
    'num_bc_tl', 'num_il_tl', 'num_op_rev_tl', 'num_rev_accts', 'num_rev_tl_bal_gt_0',
    'num_sats', 'num_tl_90g_dpd_24m', 'num_tl_op_past_12m', 'pct_tl_nvr_dlq',
    'percent_bc_gt_75', 'tot_hi_cred_lim', 'total_bal_ex_mort',
    'total_il_high_credit_limit', 'collections_12_mths_ex_med',
    'chargeoff_within_12_mths', 'pub_rec_bankruptcies', 'tax_liens', 'new_total_rev_hi_lim',
    'new_revol_bal', 'new_revol_util', 'new_bc_open_to_buy', 'new_total_bc_limit',
    'new_bc_util', 'new_all_util', 'new_state', 'new_purpose', 'new_emp_length',
    'new_home_ownership', 'new_verification_status', 'loan_status_N'
]

df = data1[cols]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1792282 entries, 0 to 1792281
Data columns (total 50 columns):
 #   Column                      Dtype
---  ------                      -----
 0   loan_amnt                   int64
 1   funded_amnt                 int64
 2   term                        int64
 3   int_rate                    float64
 4   installment                 float64
 5   annual_inc                  float64
 6   dti                         float64
 7   delinq_2yrs                 int64
 8   earliest_cr_line            datetime64[ns]
 9   fico_range_high             int64
 10  open_acc                    int64
 11  pub_rec                     int64
 12  total_acc                   int64
 13  inq_fi                      int64
 14  total_cu_tl                 int64
 15  mo_sin_old_il_acct          int64
 16  mo_sin_old_rev_tl_op        int64
 17  mort_acc                    int64
 18  num_accts_ever_120_pd       int64
 19  num_bc_sats                 int64
 20  num_bc_tl                   int64
 21  num_il_tl                   int64
 22  num_op_rev_tl               int64
 23  num_rev_accts               int64
 24  num_rev_tl_bal_gt_0         int64
 25  num_sats                    int64
 26  num_tl_90g_dpd_24m          int64
 27  num_tl_op_past_12m          int64
 28  pct_tl_nvr_dlq              float64
 29  percent_bc_gt_75            float64
 30  tot_hi_cred_lim             int64
 31  total_bal_ex_mort           int64
 32  total_il_high_credit_limit  int64
 33  collections_12_mths_ex_med  int64
 34  chargeoff_within_12_mths    int64
 35  pub_rec_bankruptcies        int64
 36  tax_liens                   int64
 37  new_total_rev_hi_lim        float64
 38  new_revol_bal               float64
 39  new_revol_util              float64
 40  new_bc_open_to_buy          float64
 41  new_total_bc_limit          float64
 42  new_bc_util                 float64
 43  new_all_util                float64
 44  new_state                   int64
 45  new_purpose                 category
 46  new_emp_length              category
 47  new_home_ownership          category
 48  new_verification_status     category
 49  loan_status_N               int64
dtypes: category(4), datetime64[ns](1), float64(13), int64(32)
memory usage: 635.8 MB

In [ ]:
df.isna().sum()

loan_amnt                         0
funded_amnt                       0
term                              0
int_rate                          0
installment                       0
annual_inc                        0
dti                               0
delinq_2yrs                       0
earliest_cr_line                  0
fico_range_high                   0
open_acc                          0
pub_rec                           0
total_acc                         0
inq_fi                            0
total_cu_tl                       0
mo_sin_old_il_acct                0
mo_sin_old_rev_tl_op              0
mort_acc                          0
num_accts_ever_120_pd             0
num_bc_sats                       0
num_bc_tl                         0
num_il_tl                         0
num_op_rev_tl                     0
num_rev_accts                     0
num_rev_tl_bal_gt_0               0
num_sats                          0
num_tl_90g_dpd_24m                0
num_tl_op_past_12m                0
pct_tl_nvr_dlq                    0
percent_bc_gt_75                  0
tot_hi_cred_lim                   0
total_bal_ex_mort                 0
total_il_high_credit_limit        0
collections_12_mths_ex_med        0
chargeoff_within_12_mths          0
pub_rec_bankruptcies              0
tax_liens                         0
new_total_rev_hi_lim           8166
new_revol_bal                     0
new_revol_util                    0
new_bc_open_to_buy                0
new_total_bc_limit            26228
new_bc_util                       0
new_all_util                      0
new_state                         0
new_purpose                       0
new_emp_length                    0
new_home_ownership                0
new_verification_status           0
loan_status_N                     0
dtype: int64

In [ ]:
df.shape

(1792282, 50)

In [ ]:
df.head()

,loan_amnt,funded_amnt,term,int_rate,installment,annual_inc,dti,delinq_2yrs,earliest_cr_line,fico_range_high,open_acc,pub_rec,total_acc,inq_fi,total_cu_tl,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mort_acc,num_accts_ever_120_pd,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,tot_hi_cred_lim,total_bal_ex_mort,total_il_high_credit_limit,collections_12_mths_ex_med,chargeoff_within_12_mths,pub_rec_bankruptcies,tax_liens,new_total_rev_hi_lim,new_revol_bal,new_revol_util,new_bc_open_to_buy,new_total_bc_limit,new_bc_util,new_all_util,new_state,new_purpose,new_emp_length,new_home_ownership,new_verification_status,loan_status_N
0,5000,5000,36,0.1065,162.869995,24000.0,27.650000,0,1985-01-01,739,3,0,9,-1,-1,-1,0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1.0,-1.0,-1,-1,-1,0,0,0,0,16305.855161,13648.0,0.837,-1.01,-0.99,-1.0,83.698996,2,1,12,1,1,1
1,2500,2500,60,0.1527,59.830002,30000.0,1.000000,0,1999-04-01,744,3,0,4,-1,-1,-1,0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1.0,-1.0,-1,-1,-1,0,0,0,0,17946.809125,1687.0,0.094,-1.01,-0.99,-1.0,9.394951,2,2,2,1,2,0
2,2400,2400,36,0.1596,84.330002,12252.0,8.720000,0,2001-11-01,739,2,0,10,-1,-1,-1,0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1.0,-1.0,-1,-1,-1,0,0,0,0,3001.015185,2956.0,0.985,-1.01,-0.99,-1.0,98.499501,2,3,12,1,3,1
3,10000,10000,36,0.1349,339.309998,49200.0,20.000000,0,1996-02-01,694,10,0,37,-1,-1,-1,0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1.0,-1.0,-1,-1,-1,0,0,0,0,26657.143689,5598.0,0.210,-1.01,-0.99,-1.0,20.997036,2,4,12,1,2,1
4,3000,3000,60,0.1269,67.790001,80000.0,17.940001,0,1996-01-01,699,15,0,38,-1,-1,-1,0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1.0,-1.0,-1,-1,-1,0,0,0,0,51545.451262,27783.0,0.539,-1.01,-0.99,-1.0,53.899109,0,4,3,1,2,1

In [ ]:
cat_cols = df.select_dtypes('category').columns.to_list()

In [ ]:
cat_cols

['new_purpose',
 'new_emp_length',
 'new_home_ownership',
 'new_verification_status']

In [ ]:
for col in cat_cols:
    df[col] = df[col].astype(int)

<ipython-input-18-5e6adf2ad897>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype(int)
<ipython-input-18-5e6adf2ad897>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype(int)
<ipython-input-18-5e6adf2ad897>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype(int)
<ipython-input-18-5e6adf2ad897>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype(int)

# iv 계산 함수

In [ ]:
import numpy as np
import pandas as pd

def calculate_iv(df, target):

    # 타겟 열의 결측값 제거
    df = df.dropna(subset=[target])

    # 숫자형 데이터의 결측값을 중앙값으로 채움
    numeric_cols = df.select_dtypes(include=['number']).columns
    df[numeric_cols] = df[numeric_cols].apply(lambda x: x.fillna(x.median()), axis=0)

    # 범주형 데이터의 결측값을 'missing'으로 채움
    categorical_cols = df.select_dtypes(include=['category', 'object']).columns
    df[categorical_cols] = df[categorical_cols].fillna('missing')

    # 숫자형/범주형 데이터 분리
    numeric_df = df.select_dtypes(include=['number'])
    categorical_df = df.select_dtypes(include=['category', 'object'])
    result_df = pd.DataFrame()

    num_cols = numeric_df.columns
    cat_cols = categorical_df.columns
    if target in num_cols:
        num_cols = num_cols.drop(target)
    if target in cat_cols:
        cat_cols = cat_cols.drop(target)

    # 숫자형 변수 처리
    for col in num_cols:
        try:
            qcut_labels, bins = pd.qcut(numeric_df[col], 10, retbins=True, labels=False, duplicates='drop')

            # 구간의 시작점과 끝점 추출
            bin_ranges = pd.cut(numeric_df[col], bins=bins, include_lowest=True)

            # 구간별 데이터 개수 및 good_cnt, bad_cnt 계산
            bin_counts = bin_ranges.value_counts().sort_index().reset_index()
            bin_counts = bin_counts.rename(columns={bin_counts.columns[0]: 'bins', bin_counts.columns[1]: 'count'})

            # good_cnt와 bad_cnt 계산
            good_bad_counts = df.groupby(bin_ranges, observed=False)[target].agg(
                good_cnt=lambda x: (x == 1).sum(),
                bad_cnt=lambda x: (x == 0).sum()
            ).reset_index(drop=True)

            # 결과 데이터프레임에 병합
            bin_counts.insert(0, 'column_id', col)
            bin_counts = pd.concat([bin_counts, good_bad_counts], axis=1)

            result_df = pd.concat([result_df, bin_counts])
            result_df.reset_index(drop=True, inplace=True)
        except ValueError as e:
            print(f"{col}에서 구간 오류로 인해 건너뜀: {e}")

    # 범주형 변수 처리
    for col in cat_cols:
        # 범주별 데이터 개수 및 good_cnt, bad_cnt 계산
        bin_counts = df[col].value_counts().sort_index().reset_index()
        bin_counts = bin_counts.rename(columns={bin_counts.columns[0]: 'bins', bin_counts.columns[1]: 'count'})

        # good_cnt와 bad_cnt 계산
        good_bad_counts = df.groupby(col, observed=False)[target].agg(
            good_cnt=lambda x: (x == 1).sum(),
            bad_cnt=lambda x: (x == 0).sum()
        ).reset_index(drop=True)

        # 결과 데이터프레임에 병합
        bin_counts.insert(0, 'column_id', col)
        bin_counts = pd.concat([bin_counts, good_bad_counts], axis=1)

        result_df = pd.concat([result_df, bin_counts])
        result_df.reset_index(drop=True, inplace=True)

    # 추가 계산
    # good/bad_ratio는 전체 중 각 구간의 good/bad 비율
    # good/bad_percent는 good/bad 중에 각 구간의 good/bad 비율
    result_df['bins_percent'] = result_df['count'] / len(df)
    result_df['good_ratio'] = result_df['good_cnt'] / result_df['count']
    result_df['bad_ratio'] = result_df['bad_cnt'] / result_df['count']
    good = len(df[df[target] == 1])
    bad = len(df[df[target] == 0])
    result_df['good_percent'] = result_df['good_cnt'] / good
    result_df['bad_percent'] = result_df['bad_cnt'] / bad

    # IV 값 계산
    result_df['WoE'] = np.log((result_df['good_percent'] + 1e-3) / (result_df['bad_percent'] + 1e-3))
    result_df['iv'] = result_df['WoE'] * (result_df['good_percent'] - result_df['bad_percent'])
    sum_iv = result_df.groupby(['column_id'])['iv'].sum().reset_index().rename(columns={'iv': 'total_iv'})
    df_iv = pd.merge(result_df, sum_iv, on='column_id', how='left')

    return df_iv

In [ ]:
df_iv = calculate_iv(df, 'loan_status_N')
df_iv

,column_id,bins,count,good_cnt,bad_cnt,bins_percent,good_ratio,bad_ratio,good_percent,bad_percent,WoE,iv,total_iv
0,loan_amnt,"(499.999, 4800.0]",181276,154758,26518,0.1011,0.8537,0.1463,0.1080,0.0739,0.3749,0.0128,0.0417
1,loan_amnt,"(4800.0, 6400.0]",179328,150394,28934,0.1001,0.8387,0.1613,0.1049,0.0806,0.2605,0.0063,0.0417
2,loan_amnt,"(6400.0, 8500.0]",179107,149747,29360,0.0999,0.8361,0.1639,0.1045,0.0818,0.2418,0.0055,0.0417
3,loan_amnt,"(8500.0, 10000.0]",209335,169266,40069,0.1168,0.8086,0.1914,0.1181,0.1117,0.0555,0.0004,0.0417
4,loan_amnt,"(10000.0, 12000.0]",167605,133426,34179,0.0935,0.7961,0.2039,0.0931,0.0952,-0.0227,0.0000,0.0417
...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,new_home_ownership,"(0.999, 2.0]",920143,711504,208639,0.5134,0.7733,0.2267,0.4964,0.5814,-0.1578,0.0134,0.0292
326,new_home_ownership,"(2.0, 3.0]",870738,720846,149892,0.4858,0.8279,0.1721,0.5029,0.4177,0.1852,0.0158,0.0292
327,new_home_ownership,"(3.0, 6.0]",1401,1074,327,0.0008,0.7666,0.2334,0.0007,0.0009,-0.0886,0.0000,0.0292
328,new_verification_status,"(0.999, 2.0]",1227144,957568,269576,0.6847,0.7803,0.2197,0.6680,0.7512,-0.1172,0.0097,0.0337
329,new_verification_status,"(2.0, 3.0]",565138,475856,89282,0.3153,0.8420,0.1580,0.3320,0.2488,0.2874,0.0239,0.0337

In [ ]:
iv = df_iv.sort_values(by='total_iv', ascending=False).loc[:,['column_id','total_iv']].drop_duplicates(subset='column_id', keep='first').reset_index(drop=True)
iv

                     column_id  total_iv
0                     int_rate    0.4182
1              fico_range_high    0.1023
2                          dti    0.0492
3           num_tl_op_past_12m    0.0441
4                  funded_amnt    0.0417
5                    loan_amnt    0.0417
6              tot_hi_cred_lim    0.0394
7                  installment    0.0388
8                     mort_acc    0.0371
9           new_bc_open_to_buy    0.0343
10     new_verification_status    0.0337
11          new_home_ownership    0.0292
12         num_rev_tl_bal_gt_0    0.0277
13                new_all_util    0.0224
14                  annual_inc    0.0197
15            percent_bc_gt_75    0.0197
16                 new_bc_util    0.0185
17        mo_sin_old_rev_tl_op    0.0166
18              new_revol_util    0.0163
19                      inq_fi    0.0152
20                   new_state    0.0125
21              new_emp_length    0.0095
22               num_op_rev_tl    0.0092
23                 new_purpose    0.0071
24          mo_sin_old_il_acct    0.0066
25        pub_rec_bankruptcies    0.0047
26                    num_sats    0.0045
27                 num_bc_sats    0.0041
28               new_revol_bal    0.0040
29  total_il_high_credit_limit    0.0035
30                   total_acc    0.0032
31       num_accts_ever_120_pd    0.0032
32                    open_acc    0.0031
33           total_bal_ex_mort    0.0030
34              pct_tl_nvr_dlq    0.0021
35                 total_cu_tl    0.0018
36  collections_12_mths_ex_med    0.0014
37          num_tl_90g_dpd_24m    0.0012
38                   num_bc_tl    0.0009
39                 delinq_2yrs    0.0008
40                     pub_rec    0.0006
41                   num_il_tl    0.0005
42                   tax_liens    0.0004
43               num_rev_accts    0.0003
44    chargeoff_within_12_mths    0.0001
45                        term    0.0000

# SelectKBest 추출함수

In [ ]:
import pandas as pd
import numpy as np
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.preprocessing import LabelEncoder


def select_features(df, target):

    # 결측값이 있는 컬럼 제거
    df = df.dropna(axis=1)

    # X와 y 정의
    X = df.drop(columns=[target])
    y = df[target]

    # 날짜형 데이터를 숫자형으로 변환(일)
    for column in X.select_dtypes(include=[np.datetime64]).columns:
        if pd.api.types.is_datetime64_any_dtype(X[column]):
            X[column] = X[column].dt.day

    # 범주형 데이터를 숫자형으로 변환
    label_encoders = {}
    for column in X.select_dtypes(include=['object', 'category']).columns:
        le = LabelEncoder()
        X[column] = le.fit_transform(X[column])
        label_encoders[column] = le

    # SelectKBest를 사용한 Univariate Feature Selection
    # 각 피처의 F-값(F-statistic)
    selector = SelectKBest(score_func=f_classif, k='all')
    X_new = selector.fit_transform(X, y)

    # 선택된 피처의 점수와 이름을 가져옴
    scores = selector.scores_
    features = X.columns

    # 점수와 피처 이름을 함께 정렬
    features_scores = sorted(zip(features, scores), key=lambda x: x[1], reverse=True)

    # 점수 순으로 정렬된 피처의 이름과 점수 출력
    column_id = [feature for feature, score in features_scores]
    sorted_scores = [score for feature, score in features_scores]

    return column_id, sorted_scores

In [ ]:
column_id, sorted_scores = select_features(df, 'loan_status_N')

In [ ]:
selected = pd.DataFrame({'column_id': column_id, 'sorted_scores':sorted_scores})
selected

                     column_id  sorted_scores
0                     int_rate    123386.7551
1                         term     53655.9828
2              fico_range_high     27000.4315
3                          dti     14416.6928
4           num_tl_op_past_12m     13054.4954
5      new_verification_status     10560.4468
6                  funded_amnt      9643.1124
7                    loan_amnt      9631.7610
8           new_home_ownership      8818.1382
9              tot_hi_cred_lim      8528.1663
10                    mort_acc      8513.1561
11         num_rev_tl_bal_gt_0      8270.3558
12          new_bc_open_to_buy      7710.0153
13                 installment      6487.5602
14                      inq_fi      5799.5556
15                new_all_util      5718.4203
16                 new_bc_util      5202.4601
17            percent_bc_gt_75      5056.6620
18              new_revol_util      4012.7293
19                   new_state      3484.5294
20        mo_sin_old_rev_tl_op      3174.6188
21               num_op_rev_tl      2760.9309
22              new_emp_length      2248.5947
23                    num_sats      1450.4145
24        pub_rec_bankruptcies      1339.3926
25                 new_purpose      1307.8706
26                 num_bc_sats      1285.6259
27          num_tl_90g_dpd_24m      1049.4156
28                     pub_rec       924.6486
29                    open_acc       923.3046
30               new_revol_bal       833.9007
31          mo_sin_old_il_acct       748.0426
32                  annual_inc       715.9634
33              pct_tl_nvr_dlq       562.8354
34                   total_acc       503.9356
35                 total_cu_tl       498.5145
36       num_accts_ever_120_pd       464.1714
37  collections_12_mths_ex_med       431.0041
38                 delinq_2yrs       368.5794
39                   tax_liens        54.4844
40    chargeoff_within_12_mths        34.3493
41                   num_bc_tl        32.9693
42           total_bal_ex_mort        32.5431
43               num_rev_accts        26.9375
44                   num_il_tl        12.5818
45  total_il_high_credit_limit         4.0455

In [ ]:
df.isin([np.inf, -np.inf]).sum()

loan_amnt                        0
funded_amnt                      0
term                             0
int_rate                         0
installment                      0
annual_inc                       0
dti                              0
delinq_2yrs                      0
earliest_cr_line                 0
fico_range_high                  0
open_acc                         0
pub_rec                          0
total_acc                        0
inq_fi                           0
total_cu_tl                      0
mo_sin_old_il_acct               0
mo_sin_old_rev_tl_op             0
mort_acc                         0
num_accts_ever_120_pd            0
num_bc_sats                      0
num_bc_tl                        0
num_il_tl                        0
num_op_rev_tl                    0
num_rev_accts                    0
num_rev_tl_bal_gt_0              0
num_sats                         0
num_tl_90g_dpd_24m               0
num_tl_op_past_12m               0
pct_tl_nvr_dlq                   0
percent_bc_gt_75                 0
tot_hi_cred_lim                  0
total_bal_ex_mort                0
total_il_high_credit_limit       0
collections_12_mths_ex_med       0
chargeoff_within_12_mths         0
pub_rec_bankruptcies             0
tax_liens                        0
new_total_rev_hi_lim          1692
new_revol_bal                    0
new_revol_util                   0
new_bc_open_to_buy               0
new_total_bc_limit               0
new_bc_util                      0
new_all_util                     0
new_state                        0
new_purpose                      0
new_emp_length                   0
new_home_ownership               0
new_verification_status          0
loan_status_N                    0
dtype: int64

In [ ]:
selection_df = pd.merge(selected, iv, on='column_id', how='left')
selection_df

                     column_id  sorted_scores  total_iv
0                     int_rate    123386.7551    0.4182
1                         term     53655.9828    0.0000
2              fico_range_high     27000.4315    0.1023
3                          dti     14416.6928    0.0492
4           num_tl_op_past_12m     13054.4954    0.0441
5      new_verification_status     10560.4468    0.0337
6                  funded_amnt      9643.1124    0.0417
7                    loan_amnt      9631.7610    0.0417
8           new_home_ownership      8818.1382    0.0292
9              tot_hi_cred_lim      8528.1663    0.0394
10                    mort_acc      8513.1561    0.0371
11         num_rev_tl_bal_gt_0      8270.3558    0.0277
12          new_bc_open_to_buy      7710.0153    0.0343
13                 installment      6487.5602    0.0388
14                      inq_fi      5799.5556    0.0152
15                new_all_util      5718.4203    0.0224
16                 new_bc_util      5202.4601    0.0185
17            percent_bc_gt_75      5056.6620    0.0197
18              new_revol_util      4012.7293    0.0163
19                   new_state      3484.5294    0.0125
20        mo_sin_old_rev_tl_op      3174.6188    0.0166
21               num_op_rev_tl      2760.9309    0.0092
22              new_emp_length      2248.5947    0.0095
23                    num_sats      1450.4145    0.0045
24        pub_rec_bankruptcies      1339.3926    0.0047
25                 new_purpose      1307.8706    0.0071
26                 num_bc_sats      1285.6259    0.0041
27          num_tl_90g_dpd_24m      1049.4156    0.0012
28                     pub_rec       924.6486    0.0006
29                    open_acc       923.3046    0.0031
30               new_revol_bal       833.9007    0.0040
31          mo_sin_old_il_acct       748.0426    0.0066
32                  annual_inc       715.9634    0.0197
33              pct_tl_nvr_dlq       562.8354    0.0021
34                   total_acc       503.9356    0.0032
35                 total_cu_tl       498.5145    0.0018
36       num_accts_ever_120_pd       464.1714    0.0032
37  collections_12_mths_ex_med       431.0041    0.0014
38                 delinq_2yrs       368.5794    0.0008
39                   tax_liens        54.4844    0.0004
40    chargeoff_within_12_mths        34.3493    0.0001
41                   num_bc_tl        32.9693    0.0009
42           total_bal_ex_mort        32.5431    0.0030
43               num_rev_accts        26.9375    0.0003
44                   num_il_tl        12.5818    0.0005
45  total_il_high_credit_limit         4.0455    0.0035

In [ ]:
# 지수표현법 숫자로 변환옵션
pd.set_option('display.float_format', '{:.4f}'.format)

In [ ]:
# for column in df.select_dtypes(include=['Float64', 'float32']).columns:
#     df[column] = df[column].astype('float64')

# for column in df.select_dtypes(include=['Int16', 'Int32', 'Int64']).columns:
#     df[column] = df[column].astype('int64')

In [ ]:
df = df.drop(columns=['new_total_rev_hi_lim', 'new_total_bc_limit', 'earliest_cr_line'], axis = 1).copy()

In [ ]:
df.shape

(1792282, 47)

# 모델 학습
### 1.1 학습&평가 데이터 분할

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.ensemble import RandomForestClassifier
import xgboost as xgb
import lightgbm as lgb

In [ ]:
# 타겟과 피처 분리
target = 'loan_status_N'
X = df.drop(columns=[target])
y = df[target]

# 데이터 분할
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, test_size=0.3, random_state=42)

### 1.2 모델 학습

In [ ]:
# 로지스틱회귀 모델 학습
lr_model = LogisticRegression(max_iter=100, random_state=42)
lr_model.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(random_state=42)

In [ ]:
# 랜덤포레스트 모델 학습 -> 20분 걸림,,
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [ ]:
# XGB 모델 학습
xgb_model = xgb.XGBClassifier(n_estimators=100, max_depth=5, learning_rate=0.1, random_state=42)
xgb_model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=5, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=None,
              num_parallel_tree=None, random_state=42, ...)

In [ ]:
# LightGBM 모델 학습
lgb_model = lgb.LGBMClassifier(n_estimators=100, max_depth=5, learning_rate=0.1, random_state=42)
lgb_model.fit(X_train, y_train)

[LightGBM] [Info] Number of positive: 1003396, number of negative: 251201
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.094034 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 5232
[LightGBM] [Info] Number of data points in the train set: 1254597, number of used features: 46
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.799776 -> initscore=1.384892
[LightGBM] [Info] Start training from score 1.384892
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

LGBMClassifier(max_depth=5, random_state=42)

### 1.3 타겟 예측 및 평가

In [ ]:
# 로지스틱회귀 예측 및 평가
lr_y_pred = lr_model.predict(X_test)

lr_accuracy = accuracy_score(y_test, lr_y_pred)
lr_onf_matrix = confusion_matrix(y_test, lr_y_pred)
lr_class_report = classification_report(y_test, lr_y_pred)

In [ ]:
lr_accuracy, lr_onf_matrix

(0.7997600825762295,
 array([[   157, 107500],
        [   166, 429862]]))

In [ ]:
# 랜덤포레스트 예측 및 평가
rf_y_pred = rf_model.predict(X_test)

rf_accuracy = accuracy_score(y_test, rf_y_pred)
rf_onf_matrix = confusion_matrix(y_test, rf_y_pred)
rf_class_report = classification_report(y_test, rf_y_pred)

In [ ]:
rf_accuracy, rf_onf_matrix

(0.8026465309614366,
 array([[  8729,  98928],
        [  7186, 422842]]))

In [ ]:
# XGBoost 예측 및 평가
xgb_y_pred = xgb_model.predict(X_test)

xgb_accuracy = accuracy_score(y_test, xgb_y_pred)
xgb_onf_matrix = confusion_matrix(y_test, xgb_y_pred)
xgb_class_report = classification_report(y_test, xgb_y_pred)

In [ ]:
xgb_accuracy, xgb_onf_matrix

(0.8038330993053554,
 array([[  8593,  99064],
        [  6412, 423616]]))

In [ ]:
# LightGBM 예측 및 평가
lgb_y_pred = lgb_model.predict(X_test)

lgb_accuracy = accuracy_score(y_test, lgb_y_pred)
lgb_onf_matrix = confusion_matrix(y_test, lgb_y_pred)
lgb_class_report = classification_report(y_test, lgb_y_pred)

In [ ]:
lgb_accuracy, lgb_onf_matrix

(0.8038461180802886,
 array([[  8513,  99144],
        [  6325, 423703]]))

# 모델 export

In [ ]:
import pickle


# lr모델
with open('logistic_regression_model.pkl', 'wb') as file:
    pickle.dump(lr_model, file)

# rf모델
with open('random_forest_model.pkl', 'wb') as file:
    pickle.dump(rf_model, file)

# xgb모델
with open('xgboost_model.pkl', 'wb') as file:
    pickle.dump(xgb_model, file)

# lgb모델
with open('lightgbm_model.pkl', 'wb') as file:
    pickle.dump(lgb_model, file)

# 전진선택법 & 후진제거법

<mlxtend(machine learning extensions)>
* scikit-learn의 기능을 확장하고 보완하기 위해 만들어진 패키지
* 주로 scikit-learn과 함께 사용되어, 사용자가 머신 러닝 모델을 쉽게 구현하고 평가할 수 있도록 도와줌

In [ ]:
import numpy as np
from mlxtend.feature_selection import SequentialFeatureSelector as SFS
from sklearn.datasets import make_classification
from tqdm import tqdm # 진행상황 표시
import warnings

In [ ]:
# 전진 선택법을 위한 SequentialFeatureSelector 설정
sfs_forward = SFS(lr_model,
                  k_features=10,
                  forward=True,
                  floating=False,
                  scoring='accuracy',
                  cv=2)  # 교차 검증 설정

# fit 과정에 tqdm을 사용하여 진행 상황 표시
n_features = X_train.shape[1]
with tqdm(total=n_features) as pbar:
    for i in range(n_features):
        sfs_forward = sfs_forward.fit(X_train, y_train)
        # 특성 선택 업데이트 시 진행 상황 갱신
        current_feature_set = sfs_forward.k_feature_idx_
        print(f"현재 선택된 특성: {current_feature_set}")
        pbar.update(1)

  0%|          | 0/46 [00:00<?, ?it/s]
  2%|▏         | 1/46 [00:07<05:31,  7.36s/it]

현재 선택된 특성: None

  4%|▍         | 2/46 [00:11<04:00,  5.46s/it]

현재 선택된 특성: None

  7%|▋         | 3/46 [00:14<03:11,  4.46s/it]

현재 선택된 특성: None

  9%|▊         | 4/46 [00:16<02:26,  3.50s/it]

현재 선택된 특성: None

 11%|█         | 5/46 [00:19<02:12,  3.23s/it]

현재 선택된 특성: None

 13%|█▎        | 6/46 [00:21<01:54,  2.85s/it]

현재 선택된 특성: None

 15%|█▌        | 7/46 [00:23<01:39,  2.56s/it]

현재 선택된 특성: None

 17%|█▋        | 8/46 [00:27<01:49,  2.88s/it]

현재 선택된 특성: None

 20%|█▉        | 9/46 [00:30<01:46,  2.87s/it]

현재 선택된 특성: None

 22%|██▏       | 10/46 [00:44<03:48,  6.36s/it]

현재 선택된 특성: None

 24%|██▍       | 11/46 [01:52<14:47, 25.35s/it]

현재 선택된 특성: None

 26%|██▌       | 12/46 [02:58<21:25, 37.82s/it]

현재 선택된 특성: None

 28%|██▊       | 13/46 [03:00<14:49, 26.94s/it]

현재 선택된 특성: None

 30%|███       | 14/46 [03:03<10:24, 19.52s/it]

현재 선택된 특성: None

 33%|███▎      | 15/46 [03:04<07:16, 14.09s/it]

현재 선택된 특성: None

 35%|███▍      | 16/46 [03:09<05:37, 11.27s/it]

현재 선택된 특성: None

 37%|███▋      | 17/46 [03:11<04:08,  8.57s/it]

현재 선택된 특성: None

 39%|███▉      | 18/46 [03:15<03:19,  7.11s/it]

현재 선택된 특성: None

 41%|████▏     | 19/46 [03:19<02:49,  6.29s/it]

현재 선택된 특성: None

 43%|████▎     | 20/46 [03:23<02:23,  5.50s/it]

현재 선택된 특성: None

 46%|████▌     | 21/46 [03:26<01:57,  4.69s/it]

현재 선택된 특성: None

 48%|████▊     | 22/46 [03:30<01:49,  4.57s/it]

현재 선택된 특성: None

 50%|█████     | 23/46 [03:34<01:43,  4.51s/it]

현재 선택된 특성: None

 52%|█████▏    | 24/46 [03:39<01:42,  4.66s/it]

현재 선택된 특성: None

 54%|█████▍    | 25/46 [03:43<01:31,  4.38s/it]

현재 선택된 특성: None

 57%|█████▋    | 26/46 [03:46<01:18,  3.92s/it]

현재 선택된 특성: None

 59%|█████▊    | 27/46 [03:48<01:04,  3.37s/it]

현재 선택된 특성: None

 61%|██████    | 28/46 [03:50<00:52,  2.93s/it]

현재 선택된 특성: None

 63%|██████▎   | 29/46 [03:52<00:46,  2.71s/it]

현재 선택된 특성: None

 65%|██████▌   | 30/46 [03:54<00:37,  2.33s/it]

현재 선택된 특성: None

 67%|██████▋   | 31/46 [03:56<00:32,  2.20s/it]

현재 선택된 특성: None

 70%|██████▉   | 32/46 [03:58<00:30,  2.15s/it]

현재 선택된 특성: None

 72%|███████▏  | 33/46 [03:59<00:24,  1.90s/it]

현재 선택된 특성: None

 74%|███████▍  | 34/46 [04:01<00:23,  1.94s/it]

현재 선택된 특성: None

 76%|███████▌  | 35/46 [04:03<00:20,  1.84s/it]

현재 선택된 특성: None

 78%|███████▊  | 36/46 [04:04<00:17,  1.74s/it]

현재 선택된 특성: None

 80%|████████  | 37/46 [04:06<00:15,  1.73s/it]

현재 선택된 특성: None

 83%|████████▎ | 38/46 [04:07<00:12,  1.57s/it]

현재 선택된 특성: None

 85%|████████▍ | 39/46 [04:08<00:10,  1.48s/it]

현재 선택된 특성: None

 87%|████████▋ | 40/46 [04:10<00:09,  1.63s/it]

현재 선택된 특성: None

 89%|████████▉ | 41/46 [04:12<00:08,  1.72s/it]

현재 선택된 특성: None

 91%|█████████▏| 42/46 [04:14<00:06,  1.71s/it]

현재 선택된 특성: None

 93%|█████████▎| 43/46 [04:16<00:05,  1.78s/it]

현재 선택된 특성: None

 96%|█████████▌| 44/46 [04:17<00:03,  1.73s/it]

현재 선택된 특성: None

 98%|█████████▊| 45/46 [04:19<00:01,  1.69s/it]

현재 선택된 특성: None

100%|██████████| 46/46 [04:22<00:00,  5.70s/it]

현재 선택된 특성: None

In [ ]:
# # 후진제거법
# # tqdm을 사용하여 후진 제거법 적용
# sfs_backward = SFS(lr_model,
#                    k_features='best',
#                    forward=False,
#                    floating=False,
#                    scoring='accuracy',
#                    cv=2)

# # fit 과정에 tqdm을 사용하여 진행 상황 표시
# for i in tqdm(range(n_features)):
#     sfs_backward = sfs_backward.fit(X_train, y_train)
#     # 특성 제거 업데이트 시 진행 상황 갱신
#     current_feature_set = sfs_backward.k_feature_idx_
#     print(f"현재 선택된 특성: {current_feature_set}")

In [ ]:
# 선택된 특성 인덱스
selected_features_forward = sfs_forward.k_feature_idx_
print(f"전진 선택법으로 선택된 특성: {selected_features_forward}")

selected_features_backward = sfs_backward.k_feature_idx_
print(f"후진 제거법으로 선택된 특성: {selected_features_backward}")

전진 선택법으로 선택된 특성: None
후진 제거법으로 선택된 특성: None

# RFE(Recursive Feature Elimination)
모델의 성능에 기여도가 낮은 특성부터 차례대로 제거하면서 최적의 특성집합을 찾는 변수 선택 기법

In [ ]:
from sklearn.feature_selection import RFE

In [ ]:
# Selected_Features =  [False False False  True False False False False False False False False
#  False False False False False False False False False False False False
#  False False False False False False False False False False False False
#  False False False False False  True False False False False]
# Feature_Ranking =  [33 32 10  1 35 37 17  9 23 12 20 43  6 27 30 25  7 13 18 19 26 16 15 11
#  21  3  8 29 31 39 38 44 41 42  4 40 34 45 36 28 24  1 22 14  2  5]

In [ ]:
n_features_to_select = 2  # 선택할 특성의 수
rfe = RFE(estimator=lr_model, n_features_to_select=n_features_to_select)

# 훈련 데이터를 사용하여 RFE 실행
rfe.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Selected Features: [False False False  True False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False  True False False False False]
Feature Ranking: [33 32 10  1 35 37 17  9 23 12 20 43  6 27 30 25  7 13 18 19 26 16 15 11
 21  3  8 29 31 39 38 44 41 42  4 40 34 45 36 28 24  1 22 14  2  5]

In [ ]:
selected_features = rfe.support_
feature_ranking = rfe.ranking_

In [ ]:
# # 특성 중요도와 이름을 매핑하여 출력
# for i, (feature, selected, rank) in enumerate(zip(X_train.columns, selected_features, feature_ranking)):
#     status = "Selected" if selected else "Not Selected"
#     print(f"Feature {i+1}: {feature}, Status: {status}, Rank: {rank}")

# 특성 이름과 순위를 DataFrame으로 변환
feature_rank_df = pd.DataFrame({
    'column_id': X_train.columns,
    'rfe_rank': feature_ranking
})

In [ ]:
merged_df = pd.merge(feature_rank_df, selection_df, on='column_id', how='inner')
merged_df.sort_values(by='rfe_rank')

                     column_id  rfe_rank  sorted_scores  total_iv
3                     int_rate         1    123386.7551    0.4182
41                   new_state         1      3484.5294    0.0125
44          new_home_ownership         2      8818.1382    0.0292
25          num_tl_90g_dpd_24m         3      1049.4156    0.0012
34        pub_rec_bankruptcies         4      1339.3926    0.0047
45     new_verification_status         5     10560.4468    0.0337
12                      inq_fi         6      5799.5556    0.0152
16                    mort_acc         7      8513.1561    0.0371
26          num_tl_op_past_12m         8     13054.4954    0.0441
7                  delinq_2yrs         9       368.5794    0.0008
2                         term        10     53655.9828    0.0000
23         num_rev_tl_bal_gt_0        11      8270.3558    0.0277
9                     open_acc        12       923.3046    0.0031
17       num_accts_ever_120_pd        13       464.1714    0.0032
43              new_emp_length        14      2248.5947    0.0095
22               num_rev_accts        15        26.9375    0.0003
21               num_op_rev_tl        16      2760.9309    0.0092
6                          dti        17     14416.6928    0.0492
18                 num_bc_sats        18      1285.6259    0.0041
19                   num_bc_tl        19        32.9693    0.0009
10                     pub_rec        20       924.6486    0.0006
24                    num_sats        21      1450.4145    0.0045
42                 new_purpose        22      1307.8706    0.0071
8              fico_range_high        23     27000.4315    0.1023
40                new_all_util        24      5718.4203    0.0224
15        mo_sin_old_rev_tl_op        25      3174.6188    0.0166
20                   num_il_tl        26        12.5818    0.0005
13                 total_cu_tl        27       498.5145    0.0018
39                 new_bc_util        28      5202.4601    0.0185
27              pct_tl_nvr_dlq        29       562.8354    0.0021
14          mo_sin_old_il_acct        30       748.0426    0.0066
28            percent_bc_gt_75        31      5056.6620    0.0197
1                  funded_amnt        32      9643.1124    0.0417
0                    loan_amnt        33      9631.7610    0.0417
36               new_revol_bal        34       833.9007    0.0040
4                  installment        35      6487.5602    0.0388
38          new_bc_open_to_buy        36      7710.0153    0.0343
5                   annual_inc        37       715.9634    0.0197
30           total_bal_ex_mort        38        32.5431    0.0030
29             tot_hi_cred_lim        39      8528.1663    0.0394
35                   tax_liens        40        54.4844    0.0004
32  collections_12_mths_ex_med        41       431.0041    0.0014
33    chargeoff_within_12_mths        42        34.3493    0.0001
11                   total_acc        43       503.9356    0.0032
31  total_il_high_credit_limit        44         4.0455    0.0035
37              new_revol_util        45      4012.7293    0.0163

In [ ]:
# 특성 중요도 계산
# lr은 feature importance가 없기 때문에 계수로 중요도를 대체하였음
lr_importance = lr_model.coef_.flatten()
rf_importance = rf_model.feature_importances_
xgb_importance = xgb_model.feature_importances_
lgb_importance = lgb_model.feature_importances_

# 데이터프레임 생성
importance_df = pd.DataFrame({
    'column_id': X_train.columns,
    'lr_importance': lr_importance,
    'rf_importance': rf_importance,
    'xgb_importance': xgb_importance,
    'lgb_importance': lgb_importance
})
importance_df

,column_id,lr_importance,rf_importance,xgb_importance,lgb_importance
0,loan_amnt,0.0002,0.0260,0.0205,177
1,funded_amnt,-0.0003,0.0257,0.0224,57
2,term,-0.0007,0.0171,0.0779,107
3,int_rate,-0.0000,0.0670,0.3714,213
4,installment,0.0018,0.0372,0.0184,117
5,annual_inc,0.0000,0.0357,0.0122,148
6,dti,-0.0003,0.0419,0.0202,160
7,delinq_2yrs,-0.0000,0.0067,0.0069,23
8,fico_range_high,0.0021,0.0268,0.0245,100
9,open_acc,-0.0001,0.0202,0.0030,7
10,pub_rec,-0.0000,0.0051,0.0088,16
11,total_acc,0.0000,0.0278,0.0061,51
12,inq_fi,-0.0001,0.0111,0.0356,153
13,total_cu_tl,-0.0000,0.0115,0.0023,9
14,mo_sin_old_il_acct,0.0002,0.0342,0.0074,88
15,mo_sin_old_rev_tl_op,0.0005,0.0374,0.0117,188
16,mort_acc,0.0000,0.0127,0.0438,71
17,num_accts_ever_120_pd,-0.0000,0.0079,0.0080,11
18,num_bc_sats,-0.0001,0.0181,0.0073,44
19,num_bc_tl,-0.0001,0.0215,0.0035,17
20,num_il_tl,0.0000,0.0232,0.0075,41
21,num_op_rev_tl,-0.0002,0.0189,0.0037,21
22,num_rev_accts,-0.0001,0.0238,0.0048,28
23,num_rev_tl_bal_gt_0,-0.0001,0.0191,0.0212,119
24,num_sats,-0.0002,0.0192,0.0030,12
25,num_tl_90g_dpd_24m,-0.0000,0.0025,0.0069,3
26,num_tl_op_past_12m,-0.0001,0.0170,0.0311,86
27,pct_tl_nvr_dlq,-0.0003,0.0194,0.0059,30
28,percent_bc_gt_75,-0.0004,0.0173,0.0049,29
29,tot_hi_cred_lim,0.0000,0.0377,0.0217,125
30,total_bal_ex_mort,-0.0000,0.0339,0.0050,23
31,total_il_high_credit_limit,0.0000,0.0300,0.0062,30
32,collections_12_mths_ex_med,-0.0000,0.0016,0.0088,7
33,chargeoff_within_12_mths,-0.0000,0.0007,0.0000,2
34,pub_rec_bankruptcies,-0.0000,0.0039,0.0058,18
35,tax_liens,-0.0000,0.0022,0.0013,2
36,new_revol_bal,0.0000,0.0372,0.0163,144
37,new_revol_util,0.0000,0.0353,0.0041,36
38,new_bc_open_to_buy,0.0000,0.0358,0.0064,76
39,new_bc_util,-0.0002,0.0344,0.0055,33
40,new_all_util,-0.0005,0.0372,0.0046,61
41,new_state,-0.0000,0.0088,0.0351,51
42,new_purpose,-0.0000,0.0128,0.0042,29
43,new_emp_length,0.0001,0.0204,0.0259,136
44,new_home_ownership,0.0000,0.0076,0.0381,71
45,new_verification_status,0.0000,0.0086,0.0102,26

In [ ]:
feature_selection = pd.merge(merged_df, importance_df, on='column_id', how='inner')
feature_selection.sort_values(by='rfe_rank').reset_index(drop=True)

,column_id,rfe_rank,sorted_scores,total_iv,lr_importance,rf_importance,xgb_importance,lgb_importance
0,int_rate,1,123386.7551,0.4182,-0.0000,0.0670,0.3714,213
1,new_state,1,3484.5294,0.0125,-0.0000,0.0088,0.0351,51
2,new_home_ownership,2,8818.1382,0.0292,0.0000,0.0076,0.0381,71
3,num_tl_90g_dpd_24m,3,1049.4156,0.0012,-0.0000,0.0025,0.0069,3
4,pub_rec_bankruptcies,4,1339.3926,0.0047,-0.0000,0.0039,0.0058,18
5,new_verification_status,5,10560.4468,0.0337,0.0000,0.0086,0.0102,26
6,inq_fi,6,5799.5556,0.0152,-0.0001,0.0111,0.0356,153
7,mort_acc,7,8513.1561,0.0371,0.0000,0.0127,0.0438,71
8,num_tl_op_past_12m,8,13054.4954,0.0441,-0.0001,0.0170,0.0311,86
9,delinq_2yrs,9,368.5794,0.0008,-0.0000,0.0067,0.0069,23
10,term,10,53655.9828,0.0000,-0.0007,0.0171,0.0779,107
11,num_rev_tl_bal_gt_0,11,8270.3558,0.0277,-0.0001,0.0191,0.0212,119
12,open_acc,12,923.3046,0.0031,-0.0001,0.0202,0.0030,7
13,num_accts_ever_120_pd,13,464.1714,0.0032,-0.0000,0.0079,0.0080,11
14,new_emp_length,14,2248.5947,0.0095,0.0001,0.0204,0.0259,136
15,num_rev_accts,15,26.9375,0.0003,-0.0001,0.0238,0.0048,28
16,num_op_rev_tl,16,2760.9309,0.0092,-0.0002,0.0189,0.0037,21
17,dti,17,14416.6928,0.0492,-0.0003,0.0419,0.0202,160
18,num_bc_sats,18,1285.6259,0.0041,-0.0001,0.0181,0.0073,44
19,num_bc_tl,19,32.9693,0.0009,-0.0001,0.0215,0.0035,17
20,pub_rec,20,924.6486,0.0006,-0.0000,0.0051,0.0088,16
21,num_sats,21,1450.4145,0.0045,-0.0002,0.0192,0.0030,12
22,new_purpose,22,1307.8706,0.0071,-0.0000,0.0128,0.0042,29
23,fico_range_high,23,27000.4315,0.1023,0.0021,0.0268,0.0245,100
24,new_all_util,24,5718.4203,0.0224,-0.0005,0.0372,0.0046,61
25,mo_sin_old_rev_tl_op,25,3174.6188,0.0166,0.0005,0.0374,0.0117,188
26,num_il_tl,26,12.5818,0.0005,0.0000,0.0232,0.0075,41
27,total_cu_tl,27,498.5145,0.0018,-0.0000,0.0115,0.0023,9
28,new_bc_util,28,5202.4601,0.0185,-0.0002,0.0344,0.0055,33
29,pct_tl_nvr_dlq,29,562.8354,0.0021,-0.0003,0.0194,0.0059,30
30,mo_sin_old_il_acct,30,748.0426,0.0066,0.0002,0.0342,0.0074,88
31,percent_bc_gt_75,31,5056.6620,0.0197,-0.0004,0.0173,0.0049,29
32,funded_amnt,32,9643.1124,0.0417,-0.0003,0.0257,0.0224,57
33,loan_amnt,33,9631.7610,0.0417,0.0002,0.0260,0.0205,177
34,new_revol_bal,34,833.9007,0.0040,0.0000,0.0372,0.0163,144
35,installment,35,6487.5602,0.0388,0.0018,0.0372,0.0184,117
36,new_bc_open_to_buy,36,7710.0153,0.0343,0.0000,0.0358,0.0064,76
37,annual_inc,37,715.9634,0.0197,0.0000,0.0357,0.0122,148
38,total_bal_ex_mort,38,32.5431,0.0030,-0.0000,0.0339,0.0050,23
39,tot_hi_cred_lim,39,8528.1663,0.0394,0.0000,0.0377,0.0217,125
40,tax_liens,40,54.4844,0.0004,-0.0000,0.0022,0.0013,2
41,collections_12_mths_ex_med,41,431.0041,0.0014,-0.0000,0.0016,0.0088,7
42,chargeoff_within_12_mths,42,34.3493,0.0001,-0.0000,0.0007,0.0000,2
43,total_acc,43,503.9356,0.0032,0.0000,0.0278,0.0061,51
44,total_il_high_credit_limit,44,4.0455,0.0035,0.0000,0.0300,0.0062,30
45,new_revol_util,45,4012.7293,0.0163,0.0000,0.0353,0.0041,36

In [ ]:
feature_selection.to_csv('feature_selection.csv', index = False)

# RFECV (Recursive Feature Elimination with Cross Validation)
* RFE에서 선택할 변수의 개수를 정하기가 어렵다는 점을 해결하기 위해 RFECV를 사용할 수 있음
*  RFE와 마찬가지로 RFECV는 낮은 변수 중요도를 갖는 변수들을 제거하는 데, 변수를 제거하며 학습할 때마다 Cross Validation을 활용해 성능을 계산

In [ ]:
# clf = LGBMClassifier(random_state=1234, n_estimators=100, learning_rate=0.01)
# min_features_to_select = 30
# step = 10
# selector = RFECV(clf, step=step, cv=5, min_features_to_select=min_features_to_select)
# selector = selector.fit(X, y)
# selector.support_.sum()

In [ ]:
# plt.figure()
# plt.xlabel("Number of features selected")
# plt.ylabel("Cross validation score (accuracy)")
# plt.plot(
#     range(min_features_to_select, len(selector.grid_scores_)*step + min_features_to_select, step),
#     selector.grid_scores_,
# )

 변수를 100개 이상 선택하여 학습했을 때와 60개만 선택했을 때의 성능이 동일하기 때문에, 최적의 변수 개수는 60개라고 판단할 수 있음

![image.png]()